# Generated by Django 4.2.11 on 2024-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.TextField(
                blank=True, null=True, verbose_name="file_path"
            ),
        ),
    ]
